export const CATEGORY_METRICS = Object.freeze({
    aiPipelineRuns: [
        "totalPipelineRuns",
        "successfulPipelineRuns",
        "fallbackPipelineRuns",
        "failedPipelineRuns",
        "blockedPipelineRuns",
        "totalPipelineDurationMs",
        "persistedInsights",
        "fallbackInsights",
        "rawSignalsSeen",
        "scoredSignalsSeen",
        "attentionAllowedRuns",
        "attentionBlockedRuns",
        "triggerEligibleRuns",
        "triggerBlockedRuns",
        "reservationAllowedRuns",
        "reservationBlockedRuns",
    ],
    aiAgentRuns: [
        "totalAgentRuns",
        "successfulAgentRuns",
        "fallbackAgentRuns",
        "failedAgentRuns",
        "timeoutAgentRuns",
        "malformedAgentRuns",
        "totalAgentDurationMs",
    ],
    insightEvents: [
        "totalInsightEvents",
        "generatedInsights",
        "fallbackInsightEvents",
        "highSeverityInsights",
        "mediumSeverityInsights",
        "lowSeverityInsights",
    ],
    businessEvents: [
        "totalBusinessEvents",
        "sftpImportsReceived",
        "sftpImportsProcessed",
        "sftpCustomersImported",
        "sftpFinancialDataImports",
        "sftpImportsFailed",
        "customersImported",
        "customersClaimed",
        "activeCustomers",
        "insightsGenerated",
        "insightsViewed",
        "insightsAcknowledged",
        "insightsDismissed",
        "insightsExpired",
        "budgetBreaches",
        "budgetBreachesResolved",
        "anomaliesDetected",
    ],
});

export const UNIQUE_CUSTOMER_EVENT_TYPES = Object.freeze([
    "customer_imported",
    "customer_claimed",
    "customer_active",
    "insight_generated",
    "insight_viewed",
    "insight_acknowledged",
    "insight_dismissed",
    "insight_expired",
    "budget_breach",
    "budget_breach_resolved",
    "anomaly_detected",
]);

export const TELEMETRY_METRIC_DEFINITIONS = Object.freeze({
    totalPipelineRuns: { area: "intelligence", unit: "events", source: "aiPipelineRuns" },
    successfulPipelineRuns: { area: "intelligence", unit: "events", source: "aiPipelineRuns" },
    fallbackPipelineRuns: { area: "intelligence", unit: "events", source: "aiPipelineRuns" },
    failedPipelineRuns: { area: "intelligence", unit: "events", source: "aiPipelineRuns" },
    blockedPipelineRuns: { area: "intelligence", unit: "events", source: "aiPipelineRuns" },
    totalPipelineDurationMs: { area: "intelligence", unit: "milliseconds_total", source: "aiPipelineRuns" },
    persistedInsights: { area: "intelligence", unit: "events", source: "aiPipelineRuns" },
    fallbackInsights: { area: "intelligence", unit: "events", source: "aiPipelineRuns" },
    rawSignalsSeen: { area: "intelligence", unit: "signals", source: "aiPipelineRuns" },
    scoredSignalsSeen: { area: "intelligence", unit: "signals", source: "aiPipelineRuns" },
    attentionAllowedRuns: { area: "intelligence", unit: "events", source: "aiPipelineRuns" },
    attentionBlockedRuns: { area: "intelligence", unit: "events", source: "aiPipelineRuns" },
    triggerEligibleRuns: { area: "intelligence", unit: "events", source: "aiPipelineRuns" },
    triggerBlockedRuns: { area: "intelligence", unit: "events", source: "aiPipelineRuns" },
    reservationAllowedRuns: { area: "intelligence", unit: "events", source: "aiPipelineRuns" },
    reservationBlockedRuns: { area: "intelligence", unit: "events", source: "aiPipelineRuns" },
    totalAgentRuns: { area: "intelligence", unit: "events", source: "aiAgentRuns" },
    successfulAgentRuns: { area: "intelligence", unit: "events", source: "aiAgentRuns" },
    fallbackAgentRuns: { area: "intelligence", unit: "events", source: "aiAgentRuns" },
    failedAgentRuns: { area: "intelligence", unit: "events", source: "aiAgentRuns" },
    timeoutAgentRuns: { area: "intelligence", unit: "events", source: "aiAgentRuns" },
    malformedAgentRuns: { area: "intelligence", unit: "events", source: "aiAgentRuns" },
    totalAgentDurationMs: { area: "intelligence", unit: "milliseconds_total", source: "aiAgentRuns" },
    totalInsightEvents: { area: "intelligence", unit: "events", source: "insightEvents" },
    generatedInsights: { area: "intelligence", unit: "events", source: "insightEvents" },
    fallbackInsightEvents: { area: "intelligence", unit: "events", source: "insightEvents" },
    highSeverityInsights: { area: "intelligence", unit: "events", source: "insightEvents" },
    mediumSeverityInsights: { area: "intelligence", unit: "events", source: "insightEvents" },
    lowSeverityInsights: { area: "intelligence", unit: "events", source: "insightEvents" },
    totalBusinessEvents: { area: "business", unit: "events", source: "businessEvents" },
    sftpImportsReceived: { area: "data_operations", unit: "import_events", source: "businessEvents" },
    sftpImportsProcessed: { area: "data_operations", unit: "import_events", source: "businessEvents" },
    sftpCustomersImported: { area: "data_operations", unit: "import_events", source: "businessEvents" },
    sftpFinancialDataImports: { area: "data_operations", unit: "import_events", source: "businessEvents" },
    sftpImportsFailed: { area: "data_operations", unit: "import_events", source: "businessEvents" },
    customersImported: { area: "customer_activity", unit: "customer_events", source: "businessEvents" },
    customersClaimed: { area: "customer_activity", unit: "customer_events", source: "businessEvents" },
    activeCustomers: { area: "customer_activity", unit: "daily_unique_customer_events", source: "businessEvents" },
    insightsGenerated: { area: "customer_activity", unit: "customer_events", source: "businessEvents" },
    insightsViewed: { area: "customer_activity", unit: "customer_events", source: "businessEvents" },
    insightsAcknowledged: { area: "customer_activity", unit: "customer_events", source: "businessEvents" },
    insightsDismissed: { area: "customer_activity", unit: "customer_events", source: "businessEvents" },
    insightsExpired: { area: "customer_activity", unit: "customer_events", source: "businessEvents" },
    budgetBreaches: { area: "customer_activity", unit: "customer_events", source: "businessEvents" },
    budgetBreachesResolved: { area: "customer_activity", unit: "customer_events", source: "businessEvents" },
    anomaliesDetected: { area: "customer_activity", unit: "customer_events", source: "businessEvents" },
});
